server:
  port: 8999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: http://localhost:9039
          predicates:
            - Path=/api/v1/address/**
            - Header=X-auth-role, admin
          filters:
            - AuthFilter

        - id: admins-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/admin/**

        - id: articles-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/articles/**

        - id: attributes-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/attributes/**

        - id: author-service
          uri: http://localhost:9041
          predicates:
            - Path=/api/v1/author/**

        - id: bill-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/bill/**

        - id: bill_promotion-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/billPromotion/**

        - id: bill_shipping-service
          uri: http://localhost:9005
          predicates:
            - Path=/api/v1/billShipping/**

        - id: carrier-service
          uri: http://localhost:9006
          predicates:
            - Path=/api/v1/carrier/**

        - id: categories-service
          uri: http://localhost:9007
          predicates:
            - Path=/api/v1/categories/**

        - id: comments-service
          uri: http://localhost:9008
          predicates:
            - Path=/api/v1/comments/**

        - id: contacts-service
          uri: http://localhost:9009
          predicates:
            - Path=/api/v1/contacts/**

        - id: detail_bill-service
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/detailBill/**

        - id: events-service
          uri: http://localhost:9011
          predicates:
            - Path=/api/v1/events/**

        - id: keywords-service
          uri: http://localhost:9012
          predicates:
            - Path=/api/v1/keywords/**

        - id: manage_warehouse-service
          uri: http://localhost:9013
          predicates:
            - Path=/api/v1/manageWarehouse/**

        - id: menu-service
          uri: http://localhost:9014
          predicates:
            - Path=/api/v1/menu/**

        - id: password_resets-service
          uri: http://localhost:9016
          predicates:
            - Path=/api/v1/passwordReset/**

        - id: payment_method-service
          uri: http://localhost:9017
          predicates:
            - Path=/api/v1/paymentMethod/**

        - id: payments-service
          uri: http://localhost:9018
          predicates:
            - Path=/api/v1/payments/**

        - id: product-service
          uri: http://localhost:9019
          predicates:
            - Path=/api/v1/product/**

        - id: product_images-service
          uri: http://localhost:9020
          predicates:
            - Path=/api/v1/productImages/**

        - id: product_type-service
          uri: http://localhost:9042
          predicates:
            - Path=/api/v1/productType/**

        - id: products_attributes-service
          uri: http://localhost:9021
          predicates:
            - Path=/api/v1/productsAttributes/**

        - id: products_keywords-service
          uri: http://localhost:9022
          predicates:
            - Path=/api/v1/productsKeywords/**

        - id: products_promotions-service
          uri: http://localhost:9023
          predicates:
            - Path=/api/v1/productsPromotions/**

        - id: promotions-service
          uri: http://localhost:9024
          predicates:
            - Path=/api/v1/promotions/**

        - id: province-service
          uri: http://localhost:9025
          predicates:
            - Path=/api/v1/province/**

        - id: publisher-service
          uri: http://localhost:9032
          predicates:
            - Path=/api/v1/publisher/**

        - id: ratings-service
          uri: http://localhost:9026
          predicates:
            - Path=/api/v1/ratings/**

        - id: shipping-service
          uri: http://localhost:9027
          predicates:
            - Path=/api/v1/shipping/**

        - id: shipping_method-service
          uri: http://localhost:9028
          predicates:
            - Path=/api/v1/shippingMethod/**

        - id: shipping_promotion-service
          uri: http://localhost:9029
          predicates:
            - Path=/api/v1/shippingPromotion/**

        - id: shopping_cart-service
          uri: http://localhost:9038
          predicates:
            - Path=/api/v1/shoppingCart/**

        - id: slides-service
          uri: http://localhost:9030
          predicates:
            - Path=/api/v1/slides/**

        - id: statics-service
          uri: http://localhost:9031
          predicates:
            - Path=/api/v1/statics/**

        - id: user_favourite-service
          uri: http://localhost:9033
          predicates:
            - Path=/api/v1/userFavourite/**

        - id: user_promotion-service
          uri: http://localhost:9035
          predicates:
            - Path=/api/v1/userPromotion/**

        - id: users-service
          uri: http://localhost:9036
          predicates:
            - Path=/api/v1/users/**

        - id: warehouse-service
          uri: http://localhost:9037
          predicates:
            - Path=/api/v1/warehouse/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
